"""Train WholeRunPolicy from its own counterfactual full-run oracle."""
from __future__ import annotations

import argparse
import os
import random

import torch
from torch.nn import functional as F
import slaythespire as sts

from .whole_run_env import RunConfig, WholeRunEnv
from .whole_run_oracle import rank_legal_actions
from .whole_run_policy import WholeRunPolicy
from .whole_run_transformer import WholeRunTransformerPolicy


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--episodes", type=int, default=20)
    p.add_argument("--combat-sims", type=int, default=100)
    p.add_argument("--ascension", type=int, default=20)
    p.add_argument("--seed", type=int, default=960000)
    p.add_argument("--labels-per-episode", type=int, default=4,
                   help="shallow strategic-search labels per seed; keeps counterfactual rollout cost bounded")
    p.add_argument("--prefix-actions", type=int, default=0,
                   help="max own-heuristic actions before labeling; diversifies screens without external data")
    p.add_argument("--checkpoint-every", type=int, default=50)
    p.add_argument("--load", default=None)
    p.add_argument("--out", default="whole_run_policy_oracle.pt")
    p.add_argument("--model", choices=("compact", "transformer"), default="transformer")
    args = p.parse_args()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    policy = (WholeRunTransformerPolicy() if args.model == "transformer" else WholeRunPolicy()).to(device)
    if args.load:
        policy.load_state_dict(torch.load(args.load, map_location=device, weights_only=True))
    optimizer = torch.optim.Adam(policy.parameters(), lr=3e-4)
    rng = random.Random(args.seed)
    labels = 0
    for episode in range(args.episodes):
        env = WholeRunEnv(RunConfig(ascension=args.ascension, combat_sims=args.combat_sims))
        obs, done = env.reset(rng.randrange(1, 2**31)), False
        # Prefixes are generated by our own legacy heuristic only to visit
        # map/reward/shop/rest states deeper in a run. They are NOT labels;
        # every supervised target below still comes from rank_legal_actions.
        prefix_teacher = sts.Agent()
        prefix_teacher.pause_on_card_reward = False
        for _ in range(rng.randrange(args.prefix_actions + 1)):
            if env.gc.outcome != sts.GameOutcome.UNDECIDED:
                break
            if env.gc.screen_state == sts.ScreenState.BATTLE:
                env._resolve_battles()
                continue
            prefix_teacher.step_out_of_combat_policy(env.gc)
            env.steps += 1
            env._resolve_battles()
        obs = env.observation()
        losses = []
        episode_labels = 0
        while not done and episode_labels < args.labels_per_episode:
            ranked = rank_legal_actions(env.gc, args.combat_sims)
            if not ranked:
                # Some legacy multi-stage reward transitions have no public
                # action at this instant.  Discard this seed fragment rather
                # than inventing a label.
                break
            target = ranked[0][0]
            logits, _ = policy(obs)
            losses.append(F.cross_entropy(logits.unsqueeze(0), torch.tensor([target], device=device)))
            labels += 1
            episode_labels += 1
            obs, _, done, info = env.step(target)
        if not losses:
            continue
        loss = torch.stack(losses).mean()
        optimizer.zero_grad(); loss.backward(); torch.nn.utils.clip_grad_norm_(policy.parameters(), 1.0); optimizer.step()
        if episode % 5 == 0:
            print(f"episode={episode} labels={labels} loss={loss.item():.4f} floor={env.gc.floor_num}", flush=True)
        if args.checkpoint_every and (episode + 1) % args.checkpoint_every == 0:
            os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
            torch.save(policy.state_dict(), args.out + ".partial")
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    torch.save(policy.state_dict(), args.out)


if __name__ == "__main__":
    main()
